### ISSUE TITLE
Need 2.9.10 or 2.9.8 version of nodemedia client, i am getting on error while installing pod

### ISSUE THREAD

**Issue by Adnan46** [NodeMedia/NodeMediaClient-iOS#1]
[!] Error installing NodeMediaClient
[!] /usr/bin/git clone https://github.com/NodeMedia/NodeMediaClient-iOS.git /var/folders/cx/j0yh2dkx0rs562b00hr4q3v00000gq/T/d20240209-48533-1ahsf8r --template= --single-branch --depth 1 --branch 2.9.10

Cloning into '/var/folders/cx/j0yh2dkx0rs562b00hr4q3v00000gq/T/d20240209-48533-1ahsf8r'...
warning: Could not find remote branch 2.9.10 to clone.
fatal: Remote branch 2.9.10 not found in upstream origin

**Comment by Adnan46** [comment]
@illuspas I am using react-native-nodemediaclient version 0.2.20 which depends upon 2.9.10 version of [NodeMediaClient-iOS] and i cant download it due to the above issue mentioned.

**Comment by fweffort** [comment]
same here

**Comment by amitsonit** [comment]
Same issue

**Comment by HalomostGull3** [comment]
Same issue, but for 2.9.11

[!] Error installing NodeMediaClient
[!] /usr/bin/git clone https://github.com/NodeMedia/NodeMediaClient-iOS.git /var/folders/4d/55b53jk51dq308mj_j_r_wmc0000gp/T/d20240213-13431-y97yvn --template= --single-branch --depth 1 --branch 2.9.11

Cloning into '/var/folders/4d/55b53jk51dq308mj_j_r_wmc0000gp/T/d20240213-13431-y97yvn'...
warning: Could not find remote branch 2.9.11 to clone.
fatal: Remote branch 2.9.11 not found in upstream origin

Using pod v1.15.2 with ruby v3.3.0 via Homebrew

**Comment by Adnan46** [comment]
Guys, I found a temporary solution. I can provide version 2.9.8 pods of NodeMediaClient. Then, you have to download version 0.2.17 of react-native-nodemediaclient.

**Comment by nowcastv** [comment]
I am using   "react-native-nodemediaclient": "^0.2.21",   "react-native": "^0.73.0",  and getting this error when I try to run pod install 


[!] Error installing NodeMediaClient
[!] /usr/bin/git clone https://github.com/NodeMedia/NodeMediaClient-iOS.git /var/folders/gt/qqbtch3s6fxczdcdxlh1z2_m0000gn/T/d20240220-83026-bfw5id --template= --single-branch --depth 1 --branch 2.9.11

Cloning into '/var/folders/gt/qqbtch3s6fxczdcdxlh1z2_m0000gn/T/d20240220-83026-bfw5id'...
warning: Could not find remote branch 2.9.11 to clone.
fatal: Remote branch 2.9.11 not found in upstream origin

**Comment by vincemavill** [comment]
@nowcastv same here you found any solution ?

**Comment by Adnan46** [comment]
**_SOLUTION (Temporary):_**

1. Download Pods from: ==> https://github.com/Adnan46/asc-react-natve-rte-sample/tree/master/ios/Pods/NodeMediaClient
2. Place the pods' files somewhere in the project and add the path in the PodFile.
3. Install react-native-nodemediaclient@0.2.17.
4. Install pods.

Now everything will work. The latest Node Media Client may not run the project due to the latest pods is not available in the git repo.

**Comment by juanchoperezj** [comment]
Hi @Adnan46 can you elaborate a bit more on the steps to make the pod work with your repo?
I tried but is not clear to me what I need to do.

**Comment by vincemavill** [comment]
@Adnan46 hello sir, can you show a detailed procedure sir.

**Comment by vincemavill** [comment]
@juanchoperezj you found any solution?

**Comment by p29hieu** [comment]
same issue!

**Comment by vincemavill** [comment]
pls share if you have the podfile, for the temporary sollution

**Comment by vincemavill** [comment]
> **_SOLUTION (Temporary):_**
> 
> 1. Download Pods from: ==> https://github.com/Adnan46/asc-react-natve-rte-sample/tree/master/ios/Pods/NodeMediaClient
> 2. Place the pods' files somewhere in the project and add the path in the PodFile.
> 3. Install react-native-nodemediaclient@0.2.17.
> 4. Install pods.
> 
> Now everything will work. The latest Node Media Client may not run the project due to the latest pods is not available in the git repo.


 can you show a detailed procedure sir.

**Comment by Adnan46** [comment]
SOLUTION (Temporary):

1. Download Pods File from: ==> **https://www.mediafire.com/file/lysy2vwcb3neh62/NodeMediaClient.zip/file**
2. Extract the zip file and place **NodeMediaClient** pods folder in your project ios folder.
3. Add this Line in PodFile **pod 'NodeMediaClient', :path => "./NodeMediaClient"**
![image](https://github.com/NodeMedia/NodeMediaClient-iOS/assets/96617370/a1e72ff1-1687-499f-b27a-f6ee561c27e4)

4. Install react-native-nodemediaclient@0.2.17.
5. Install pods.

Follow These steps and your project will work fine, Hit Like and remember me in your prayers

**Comment by vincemavill** [comment]
@Adnan46 it shows framework not found NodeMediaClient

**Comment by juanchoperezj** [comment]
Guys, what these people did with this library is just wrong.

My advice is to move on to an alternative, I was able to use this library https://github.com/ezranbayantemur/react-native-rtmp-publisher, without changing too much the code.

cc @vincemavill

**Comment by vincemavill** [comment]
@juanchoperezj sir do you have a sample github repo, that i can follow. i tried that but there was a bug in background.
also the streamkey is required, i only use streamURL

**Comment by illuspas** [comment]
sdk v2 is no longer maintained and a new v3 compatible  #react-native-nodemediaclent is under development

**Comment by juanchoperezj** [comment]
@vincemavill checkout this [library](https://github.com/apivideo/api.video-reactnative-live-stream)

**Comment by vincemavill** [comment]
this is great @juanchoperezj thanks, God bless you.

**Comment by illuspas** [comment]
Released, please use the new version.
