### ISSUE TITLE
推流回调2007

### ISSUE THREAD

**Issue by FanPower** [NodeMedia/NodeMediaClient-iOS#10]

**Comment by FanPower** [comment]
多台设备都试过，结果相同

**Comment by illuspas** [comment]
是否另外还链接了ffmpeg库?

**Comment by FanPower** [comment]
是的，使用了ijk播放器，加载库的时候是放在nodemedia的后面的，如果放在前面会爆ffmpeg错误，所以把ijk放到后面，就出现了2007

**Comment by illuspas** [comment]
你试试不链接 ijk的libavformat.a

**Comment by zhenghx1105** [comment]
同样遇到这个问题有什么好的解决方法？

**Comment by zhenghx1105** [comment]
使用了不同版本的ffmpeg如果不链接这几个文件 ijk播放不了。怎么破？
