### ISSUE TITLE
初次安装软件，直播推流不成功。双击home强制重启才能正常。

### ISSUE THREAD

**Issue by wangjingios** [NodeMedia/NodeMediaClient-iOS#11]
初次安装软件，推流2001 但是听不到直播的声音。强制重启软件或者第二次覆盖安装就能直播声音了。如果删掉，再安装的效果和第一次安装效果一样，直播不成功。（用的demo听声音，demo收听端肯定不存在问题）。多个手机都出现这样的效果

**Comment by illuspas** [comment]
无法重现你说的这种情况,可以的话,给我的邮箱发一个你的用例来看看
