### ISSUE TITLE
cpu

### ISSUE THREAD

**Issue by wenlian2035** [NodeMedia/NodeMediaClient-iOS#12]
不知道有没有人测试过cup呢，视频画面越大cpu耗用越高，在ipad上面cup能跑到100%甚至百零几，这是什么问题呢？？怎么破？？

**Comment by illuspas** [comment]
目前是软解,硬解版本还在开发中

**Comment by illuspas** [comment]
v2.0.0 beta版本已发布,正式支持硬解码.视频编码:H.264/MPEG4,音频编码:AAC/MP3/AC3 都可以自动开启.
