### ISSUE TITLE
Digest certificate authentication

### ISSUE THREAD

**Issue by yasirbasharat** [NodeMedia/NodeMediaClient-iOS#15]
How can we use digest authentication? I have to stream CCTV camera but it needs to be authenticated with Digest certificate.

Could you please help

**Comment by illuspas** [comment]
You can try setInputUrl such as "rtsp://user:pass@x.x.x.x/VideoString"

**Comment by yasirbasharat** [comment]
I tried this. Connection was successful but no stream get play.
im trying to play rtsp stream from CCTV camera. I hope this is possible with your framework.

**Comment by illuspas** [comment]
Can you provide the RTSP address for public network access?
Email me ,illuspas[at]gmail.com

**Comment by yasirbasharat** [comment]
email sent
