### ISSUE TITLE
Can not mute the audio in NodePlayer

### ISSUE THREAD

**Issue by DrMoriarty** [NodeMedia/NodeMediaClient-iOS#16]
Hello!
I'm using NodePlayer in order to play RTSP video with audio channel. I try to set `nodePlayer.audioEnable = false` but it doesn't mute the audio. I also tried `receiveAudio` property, but it seems to be disabling audio stream receiving at all.
How can I mute and then again start audio playing in NodePlayer?

**Comment by illuspas** [comment]
Please use pod update to v2.4.2

**Comment by DrMoriarty** [comment]
@illuspas thank you!
