### ISSUE TITLE
Not open view camera in react-native

### ISSUE THREAD

**Issue by Duyanh140900** [NodeMedia/NodeMediaClient-iOS#2]
I use react-native-nodemediaclent and use NodeMediaClient 3.2.5. But when I do a live stream, I can't open the image from the camera on the phone screen, it appears a blank screen even though the live stream is still going perfectly. Who can help me ? I sincerely thank. Below is my code
<img width="966" alt="Screenshot 2024-02-27 at 15 34 09" src="https://github.com/NodeMedia/NodeMediaClient-iOS/assets/56527413/36f8abc1-003e-4270-bd8b-75fa4b8a46fe">

**Comment by illuspas** [comment]
The new sdk v3 compatible react-native-nodemediaclent is still in development

**Comment by Duyanh140900** [comment]
Is there no way for me to use it now?
When will it be published?

**Comment by illuspas** [comment]
Released, please use the new version.
