### ISSUE TITLE
模拟器播放rtsp很正常，而且内存占用也不高，但是真机测试无图像。

### ISSUE THREAD

**Issue by NullWorld** [NodeMedia/NodeMediaClient-iOS#21]
模拟器播放rtsp流很正常，而且内存占用也不高，但是真机测试无图像。内存也没有任何增长。

**Comment by NullWorld** [comment]
地址。。。。rtsp://admin:cj123456@180.167.49.230:554/Streaming/Channels/101

**Comment by illuspas** [comment]
开选项，用TCP传输

**Comment by illuspas** [comment]
https://github.com/NodeMedia/NodeMediaClient-iOS/blob/master/NodeMediaClient/NodeMediaClient.framework/Headers/NodePlayer.h#L53

**Comment by NullWorld** [comment]
谢了，好了。

**Comment by NullWorld** [comment]
可以了。。
