### ISSUE TITLE
Not displaying a video

### ISSUE THREAD

**Issue by dagba** [NodeMedia/NodeMediaClient-iOS#26]
Hi i`ve tried both example and my own integration of a framework but rtsp stream doesnt play and no image at all

**Comment by aymather** [comment]
I am having the same problem on both ios and android, I am only seeing a white screen without any display from the camera. Any solutions to this?

**Comment by dagba** [comment]
> I am having the same problem on both ios and android, I am only seeing a white screen without any display from the camera. Any solutions to this?

text me, if u need help, i know a solution

**Comment by aymather** [comment]
@dagba I sent you an email at dagdk95@gmail.com, your help would be greatly appreciated!
