### ISSUE TITLE
求助--在应用中播放RTMP数据会崩溃

### ISSUE THREAD

**Issue by scoon109294** [NodeMedia/NodeMediaClient-iOS#3]
使用Demo过程中，不论推流还是播放都没有问题，但是接入自己的项目中后发现推流没有问题，但是播放会存在一些问题，只要一连接成功，开始播放就会崩溃。
信息如下：
**\* thread #28: tid = 0x7e12a, 0x0000000100d13f6c iChat`ff_h264_decode_seq_parameter_set + 44, stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
- frame #0: 0x0000000100d13f6c iChat`ff_h264_decode_seq_parameter_set + 44
  
  frame #1: 0x0000000100f99e08 iChat`decode_nal_units + 2212
  
  frame #2: 0x0000000100f9947c iChat`ff_h264_decode_extradata + 268
  
  frame #3: 0x0000000100f9c7e4 iChat`h264_parse + 156
  
  frame #4: 0x0000000100ff57c4 iChat`av_parser_parse2 + 260
  
  frame #5: 0x0000000101039dec iChat`parse_packet + 316
  
  frame #6: 0x0000000101035f60 iChat`read_frame_internal + 880
  
  frame #7: 0x00000001010358e4 iChat`av_read_frame + 72
  
  frame #8: 0x0000000100f72c44 iChat`MediaPlayerThread + 820
  
  frame #9: 0x00000001998841b0 libsystem_pthread.dylib`_pthread_body + 168
  
  frame #10: 0x0000000199884108 libsystem_pthread.dylib`_pthread_start + 140
  
  frame #11: 0x00000001998817b0 libsystem_pthread.dylib`thread_start + 4

求大神帮忙，看下是什么问题？

**Comment by illuspas** [comment]
你的项目里链接过ffmpeg库了没

**Comment by scoon109294** [comment]
我还加入了一些第三方的库，可能会有？

**Comment by scoon109294** [comment]
要确保都没链接过吗？我再去排查一下。
