### ISSUE TITLE
when installing pods on step NodeMediaClient (2.9.11) I get an error

### ISSUE THREAD

**Issue by korkija** [NodeMedia/NodeMediaClient-iOS#3]
I use "react-native-nodemediaclient": "^0.2.21"
after yarn install
on pos install catch an error.

Do you have old versions?

[!] Error installing NodeMediaClient
[!] /usr/bin/git clone https://github.com/NodeMedia/NodeMediaClient-iOS.git /var/folders/f2/ys33tltn4rl9z5w_8w7bkb5h0000gp/T/d20240408-49515-1xealao --template= --single-branch --depth 1 --branch 2.9.11

Cloning into '/var/folders/f2/ys33tltn4rl9z5w_8w7bkb5h0000gp/T/d20240408-49515-1xealao'...
warning: Could not find remote branch 2.9.11 to clone.
fatal: Remote branch 2.9.11 not found in upstream origin

**Comment by worker722** [comment]
Same with me this error.
React native 0.66

**Comment by korkija** [comment]
on my project 
    "react": "17.0.1",
    "react-native": "^0.64.4",
when I decided to update library to "react-native-nodemediaclient": "0.3.4",
after installing the pods. the library was completely removed from Podfile.lock
removed
 - NodeMediaClient (2.9.11)
 
   - react-native-nodemediaclient (0.2.21):
    - NodeMediaClient (= 2.9.11)
    - React
    - react-native-nodemediaclient/RCTNodeMediaClient (= 0.2.21)
  - react-native-nodemediaclient/RCTNodeMediaClient (0.2.21):
    - NodeMediaClient (= 2.9.11)
    - React
    
     - react-native-nodemediaclient (from `../node_modules/react-native-nodemediaclient`)
 
     - NodeMediaClient
     
       react-native-nodemediaclient:
    :path: "../node_modules/react-native-nodemediaclient"
    
      NodeMediaClient: 18bf1853c3d4e1d061c685f0dadb09518f64417a
      react-native-nodemediaclient: d910db5a5a503e117aaa5bd67d29f7d2375e883b
