### ISSUE TITLE
Landscape mode orientation stretch issue in iOS notch devices.

### ISSUE THREAD

**Issue by dharmik** [NodeMedia/NodeMediaClient-iOS#32]
In iPhone **Notch Devices** like iPhone X, iPhone XR, When the device having **Landscape mode** the camera preview is **Stretched**. Works fine in portrait mode. 
For the reference, 
**An issue in Landscape:** [Landscape](https://www.dropbox.com/s/kd423w5uh0c39f4/Landscape_Mode_Cam_Preview.jpeg)

**Not an issue in Portrait:** [Portrait](https://www.dropbox.com/s/kwfyalzaw0zp8j3/Portrait_Mode_Cam_Preview.jpeg)
Anyone having an idea about that landscape mode stretch issue?

**Comment by thiennguyen2428** [comment]
So do I, anyone have solution ?

**Comment by mlund01** [comment]
+1

**Comment by mlund01** [comment]
@illuspas any thoughts on this?

**Comment by diegotrigo** [comment]
Nearly one year since this was opened. Did anyone find a solution?
