### ISSUE TITLE
EXC_BAD_ACCESS occured when first come to initialize either the NodePublisher or NodePlayer

### ISSUE THREAD

**Issue by hownaskie** [NodeMedia/NodeMediaClient-iOS#39]
<img width="790" alt="Screen Shot 2020-03-13 at 6 08 04 PM" src="https://user-images.githubusercontent.com/6029968/76611558-ad291e00-6555-11ea-9924-dd13ddf7ce21.png">

I just only updating my version of NodeMediaClient then i build after the update and everytime I initialize the NodePublisher or NodePlayer it always like that

**Comment by illuspas** [comment]
Please update to 2.7.2
