### ISSUE TITLE
服务端为red5 1.0.6，播放无声

### ISSUE THREAD

**Issue by illuspas** [NodeMedia/NodeMediaClient-iOS#4]
服务端环境：red5-server-v1.0.6
客户端环境：iOS-v0.5.0 Android-v0.9.0
操作步骤： 客户端A先发布视频，客户端B再播放，有画面，没有声音。如果B先播放，A再发布视频，则没有问题

**Comment by illuspas** [comment]
已修复，随iOS-0.5.1 Android-0.9.1发布修复版

**Comment by devicten** [comment]
請問 iOS0.5.1版與 Android-0.9.1何時會發布?
