### ISSUE TITLE
播放器闪退

### ISSUE THREAD

**Issue by yecoco** [NodeMedia/NodeMediaClient-iOS#42]
在ios上播放器播放一个rtmp直播流时, 当加载不出视频时退出, 调用stop会出现闪退, 加载出视频时, 就不会出现闪退, 版本2.7.3

**Comment by illuspas** [comment]
并没有复现出来，你试试
https://github.com/NodeMedia/QLive-iOS
看能否出现

或贴一下你的使用代码

**Comment by yecoco** [comment]
当我添加了这行代码[_np setAudioEnable:true];就会出现无视频销毁播放器闪退

**Comment by yecoco** [comment]
> 并没有复现出来，你试试
> https://github.com/NodeMedia/QLive-iOS
> 看能否出现
> 
> 或贴一下你的使用代码

当我添加了这行代码[_np setAudioEnable:true];就会出现无视频销毁播放器闪退

**Comment by yecoco** [comment]
> 并没有复现出来，你试试
> https://github.com/NodeMedia/QLive-iOS
> 看能否出现
> 
> 或贴一下你的使用代码

第一次销毁不会,第二次就出现闪退

**Comment by illuspas** [comment]
还真是
