### ISSUE TITLE
最新版本是不支持armv7 32位的机器了吗, iphone 5直接崩溃

### ISSUE THREAD

**Issue by yecoco** [NodeMedia/NodeMediaClient-iOS#45]
iphone 5 崩溃在 ff_prefetch_arm

xxxxxxx `ff_prefetch_arm:
->  0x74865c <+0>: .long  0xf8901e52                ; unknown opcode
    0x748660 <+4>: strmi  pc, [r8], #-0
    0x748664 <+8>: .long  0x4770d1fa                ; unknown opcode

**Comment by illuspas** [comment]
根据Apple的建议，已经停止了armv7和i386架构的支持。
iphone5发布于8年以前了，现在还有这个需求吗？

**Comment by yecoco** [comment]
> 根据Apple的建议，已经停止了armv7和i386架构的支持。
> iphone5发布于8年以前了，现在还有这个需求吗？

哦哦，那也没事，只是内部使用到了iPhone 5，采用老版本播放器就行
