### ISSUE TITLE
How to Play in background?

### ISSUE THREAD

**Issue by jxxnnee** [NodeMedia/NodeMediaClient-iOS#56]
I want to play in background
But, There are no functions or variables associated with it.

What do I need to play in the background?

**Comment by rezq2009** [comment]
any update about play in background on IOS ? 

actually looking for add play in background on IOS use react-native-nodemediaclient

**Comment by rezq2009** [comment]
@jxxnnee  actually play in background is working well you only need to configure your app to continue playing audio when it goes into the background via Xcode


https://developer.apple.com/documentation/avfoundation/media_playback_and_selection/creating_a_basic_video_player_ios_and_tvos/enabling_background_audio

!! Note it may not work in debug mode . .. but don't worry its working in released mode
