### ISSUE TITLE
目前可以 Play多個URL，放入不同UIView?

### ISSUE THREAD

**Issue by RockyDavid** [NodeMedia/NodeMediaClient-iOS#6]
我使用範例改寫，宣告兩個LivePlayer，lp1、lp2並setUIView各自的UIView，startPlay各自的URL，發現兩個串流的影像會交替出現於後者的UIView中

**Comment by illuspas** [comment]
目前版本不支持多播

**Comment by yuyangdexue** [comment]
你好 我想研究一下原理 看不到源码  不知道 你这个商用是什么情况

**Comment by wangsuikang** [comment]
可以是实现多人会议吗？
